---
functional:
  - Реализовать регистрацию пользователя через логин/email/пароль  
  - Реализовать регистрацию через OAuth (GitHub/Discord)  
  - Обеспечить вход по email/паролю  
  - Обеспечить вход через OAuth (GitHub/Discord)  
  - Организовать баттлы между игроками  
  - Реализовать синхронизацию кода между соперниками  
  - Предоставить публичный доступ к просмотру активных баттлов  
  - Внедрить систему рейтинга игроков  
  - Реализовать режим игры против бота  
  - Обеспечить приватные игры по пригласительной ссылке (кнопка уведомлений с количеством приглашений, отмена приглашения)
  - Предоставить выбор таймера для игры  
  - Предоставить выбор языка программирования (Clojure, Cpp, Csharp, Dart, Elixir, Go, Haskell, Java, Javascript, Kotlin, Php, Python, Ruby, Rust, Typescript)
  - Предоставить выбор уровня сложности  
  - Реализовать случайный выбор задачи
  - Реализовать выбор задачи из каталога  
  - Внедрить теги для упрощения поиска задачи  
  - Обеспечить наличие условия задач на русском и английском языках  
  - Реализовать чат для зарегистрированных пользователей 
  - Предоставить доступ к записям завершённых игр
  - Оформить запись игр в виде плеера (перемотка, скорость 1х\2х, копирование ссылки)
  - Реализовать создание турниров (с настройками даты начала, публичности, описанием и количеством игроков)
  - Реализовать систему кланов
  - Реализовать пробный баттл без регистрации на стартовой странице
  - Реализовать возможность создания задач для баттлов
  - Реализовать возможность создания пакетов задач (с уникальным именем и возможностью скрывать и редактировать)
  - Реализовать доступ к архиву созданных задач для баттлов 
  
non-functional:
  - Обеспечить UX-оптимизацию
  - Обеспечить высокую скорость загрузки  
  - Гарантировать безопасность данных (HTTPS, шифрование)  
  - Реализовать адаптивный мобильный дизайн  
  - Обеспечить кросс-браузерную совместимость (поддержка основных версий Google Chrome, Safari, Firefox) 
  - Поддерживать нагрузку до 1000 одновременных пользователей  

implicit:
  - Предоставить возможность редактирование профиля пользователя (никнейм, клан, язык программирования, звуковой тип, ссылки discord & Github) 
  - Реализовать систему начисления рейтинга за победы ( +n очков за победу, -n очков за проигрышь и сдачу)
  - Внедрить лидерборды с периодами (неделя/месяц/всё время) и сортировкой (рейтинг, игр сыгнано, дата регистрации)
  - Спроектировать редактор кода в виде проигрывателя
  - Валидация данних при регистрации
  - Валидация nickname - 3-16 символов, латиница/цифры/подчёркивание, начало с буквы
  - Валидация email - соответствие формату *@*.*
  - Валидация пароля - 6-16 символов, минимум 1 спецсимвол
  - Подтверждение пароля - точное совпадение с паролем
  - Валидация данных при входе
  - Реализовать возможность восстановления доступа при потере пароля
  - Реализовать проверку кода в вкладке output (с доступом к ней и в записи игры)
