---
functional:
#  - 1. Реализовать регистрацию пользователя через логин/email/пароль  
#  - 2. Реализовать регистрацию через OAuth (GitHub/Discord)  
#  - 3. Обеспечить вход по email/паролю  
#  - 4. Обеспечить вход через OAuth (GitHub/Discord)  
  - 5. Организовать баттлы между игроками  
  - 6. Реализовать синхронизацию кода между соперниками  
  - 7. Предоставить публичный доступ к просмотру активных баттлов  
  - 8. Внедрить систему рейтинга игроков  
  - 9. Реализовать режим игры против бота  
  - 10. Обеспечить приватные игры по пригласительной ссылке  
  - 11. Предоставить выбор таймера для игры  
  - 12. Предоставить выбор языка программирования  
  - 13. Предоставить выбор уровня сложности  
  - 14. Реализовать случайный выбор задачи
  - 15. Реализовать выбор задачи из каталога  
  - 16. Внедрить теги для упрощения поиска задачи  
  - 17. Обеспечить условия задач на русском и английском языках  
  - 18. Реализовать чат для зарегистрированных пользователей  
  - 19. Предоставить доступ к записям завершённых игр (историю игр)
#  - 20. Реализовать турниры
  - 21. Реализовать возможность создания кланов
  - 22. Реализовать возможность пробного баттла без регистрации

non-functional:
  - 1. Обеспечить UX-оптимизацию
  - 2. Обеспечить высокую скорость загрузки  
  - 3. Гарантировать безопасность данных (HTTPS, шифрование)  
  - 4. Реализовать адаптивный мобильный дизайн  
  - 5. Обеспечить кросс-браузерную совместимость  
  - 6. Поддерживать нагрузку до 1000 одновременных пользователей  

implicit:
  - 1. Предоставить возможность редактирование профиля пользователя  
  - 2. Реализовать систему начисления рейтинга за победы  
  - 3. Внедрить лидерборды с периодами (неделя/месяц/всё время)  
  - 4. Спроектировать редактор кода в виде проигрывателя
  - 5. Валидация данних при регистрации
  - 6. Валидация данных при входе
  - 7. Реализовать возможность восстановления доступа при потере пароля
