---
functional:
  - 1. Реализовать регистрацию пользователя через логин/email/пароль  
  - 2. Реализовать регистрацию через OAuth (GitHub/Discord)  
  - 3. Обеспечить вход по email/паролю  
  - 4. Обеспечить вход через OAuth (GitHub/Discord)  
  - 5. Организовать баттлы между игроками  
  - 6. Реализовать синхронизацию кода между соперниками  
  - 7. Предоставить публичный доступ к просмотру активных баттлов  
  - 8. Внедрить систему рейтинга игроков  
  - 9. Реализовать режим игры против бота  
  - 10. Обеспечить приватные игры по пригласительной ссылке (кнопка уведомлений с количеством приглашений, отмена приглашения)
  - 11. Предоставить выбор таймера для игры  
  - 12. Предоставить выбор языка программирования (Clojure, Cpp, Csharp, Dart, Elixir, Go, Haskell, Java, Javascript, Kotlin, Php, Python, Ruby, Rust, Typescript)
  - 13. Предоставить выбор уровня сложности  
  - 14. Реализовать случайный выбор задачи
  - 15. Реализовать выбор задачи из каталога  
  - 16. Внедрить теги для упрощения поиска задачи  
  - 17. Обеспечить наличие условия задач на русском и английском языках  
  - 18. Реализовать чат для зарегистрированных пользователей 
  - 19. Предоставить доступ к записям завершённых игр
  - 19.1 Оформить запись игр в виде плеера (перемотка, скорость 1х\2х, копирование ссылки)
  - 20. Реализовать создание турниров (с настройками даты начала, публичности, описанием и количеством игроков)
  - 21. Реализовать систему кланов
  - 22. Реализовать пробный баттл без регистрации на стартовой странице
  - 23. Реализовать возможность создания задач для баттлов
  - 24. Реализовать возможность создания пакетов задач (с уникальным именем и возможностью скрывать и редактировать)
  - 24. Реализовать доступ к архиву созданных задач для баттлов 
  
non-functional:
  - 1. Обеспечить UX-оптимизацию
  - 2. Обеспечить высокую скорость загрузки  
  - 3. Гарантировать безопасность данных (HTTPS, шифрование)  
  - 4. Реализовать адаптивный мобильный дизайн  
  - 5. Обеспечить кросс-браузерную совместимость (поддержка основных версий Google Chrome, Safari, Firefox) 
  - 6. Поддерживать нагрузку до 1000 одновременных пользователей  

implicit:
  - 1. Предоставить возможность редактирование профиля пользователя (никнейм, клан, язык программирования, звуковой тип, ссылки discord & Github) 
  - 2. Реализовать систему начисления рейтинга за победы ( +n очков за победу, -n очков за проигрышь и сдачу)
  - 3. Внедрить лидерборды с периодами (неделя/месяц/всё время) и сортировкой (рейтинг, игр сыгнано, дата регистрации)
  - 4. Спроектировать редактор кода в виде проигрывателя
  - 5. Валидация данних при регистрации
  - 5.1. Валидация nickname - 3-16 символов, латиница/цифры/подчёркивание, начало с буквы
  - 5.2. Валидация email - соответствие формату *@*.*
  - 5.3. Валидация пароля - 6-16 символов, минимум 1 спецсимвол
  - 5.4. Подтверждение пароля - точное совпадение с паролем
  - 6. Валидация данных при входе
  - 7. Реализовать возможность восстановления доступа при потере пароля
  - 8. Реализовать проверку кода в вкладке output (с доступом к ней и в записи игры)
